sudo: false
languague: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i -g npm
before_script:
  - npm prune
script:
  - npm run test:single
after_success:
  - npm run semantic-release
